name: "oci"
version: "1.0.8"
description: |-
  Get packaged Charts from OCI, support both downloader & proxy mode
command: "bin/helm-oci"
downloaders:
  - command: "bin/helm-oci"
    protocols:
      - "oci+login"
hooks:
  install: "echo 'hi' && $HELM_PLUGIN_DIR/install-binary.sh"
  update: "echo 'update' && $HELM_PLUGIN_DIR/install-binary.sh"
